// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

'use client';

import { getFirebaseConfig } from '@/firebase/config';
import { getApp, getApps, initializeApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

export * from '@/firebase/provider';
export * from '@/firebase/client-provider';
export * from '@/firebase/auth/use-user';
export * from '@/firebase/firestore/use-collection';
export * from '@/firebase/firestore/use-doc';

type FirebaseServices = {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
};

export function initializeFirebase(): FirebaseServices {
  const firebaseConfig = getFirebaseConfig();
  const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
  const auth = getAuth(app);
  const firestore = getFirestore(app);
  return { app, auth, firestore };
}
